#!/usr/bin/env bash

set -e

ROOT_DIR=`pwd`
INSTALL_DIR=$1

APACHE2_DIR=${INSTALL_DIR}

mkdir -p "${INSTALL_DIR}"
# TODO: change to dependency configured externally 
whack get-package 'git+https://github.com/mwilliamson/whack-package-apache2.git#afaf200' "${APACHE2_DIR}"

build_libxml() {
    # TODO: package libxml separately
    
    LIBXML_SRC_DIR=libxml2-${LIBXML_VERSION}
    LIBXML_DIR=${INSTALL_DIR}/libxml2
    
    tar xzf libxml2-${LIBXML_VERSION}.tar.gz
    cd ${LIBXML_SRC_DIR}
    ./configure --prefix=${LIBXML_DIR}
    make
    make install
    
    cd ${ROOT_DIR}
}

build_libmcrypt() {
    LIBMCRYPT_DIR=${INSTALL_DIR}/libmcrypt
    
    tar xzf libmcrypt-${LIBMCRYPT_VERSION}.tar.gz
    cd libmcrypt-${LIBMCRYPT_VERSION}
    ./configure --prefix=${LIBMCRYPT_DIR}
    make
    make install
    
    cd ${ROOT_DIR}
}

add_php_arg() {
    PHP_ARGS=("${PHP_ARGS[@]}" "$1")
}

build_php() {
    build_libxml
    if [ -n "$WITH_LIBMCRYPT" ]; then
        build_libmcrypt
    fi
    
    PHP_SRC_DIR=php-${PHP_VERSION}
    PHP_DIR=${INSTALL_DIR}
    
    tar xzf php-${PHP_VERSION}.tar.gz
    cd ${PHP_SRC_DIR}
    
    PHP_ARGS=(
        --prefix=${PHP_DIR}
        --bindir=${PHP_DIR}/.bin
        --sbindir=${PHP_DIR}/.bin
        --with-apxs2=${APACHE2_DIR}/.bin/apxs
        --with-libxml-dir=${LIBXML_DIR}
        --with-mysql=mysqlnd
    )
    
    if [ -n "$WITH_LIBMCRYPT" ]; then
        add_php_arg "--with-mcrypt=${LIBMCRYPT_DIR}"
    fi
    
    if [ -n "$WITH_MBSTRING" ]; then
        add_php_arg --enable-mbstring
    fi
    
    if [ -n "$WITH_PDO_MYSQL" ]; then
        add_php_arg --with-pdo-mysql=mysqlnd
    fi
    
    if [ -n "$WITH_PGSQL" ]; then
        add_php_arg --with-pgsql
    fi
    
    if [ -n "$WITH_PDO_PGSQL" ]; then
        add_php_arg --with-pdo-pgsql
    fi
    
    ./configure "${PHP_ARGS[@]}"
    make
    make install
    cp php.ini-production ${PHP_DIR}/lib/php.ini
    
    cd ${ROOT_DIR}
}

build_php

#~ echo 'LoadModule php5_module modules/libphp5.so' >> ${INSTALL_DIR}/conf/httpd.conf
echo '<FilesMatch \.php$>
    SetHandler application/x-httpd-php
</FilesMatch>' >> ${INSTALL_DIR}/conf/httpd.conf
