#!/usr/bin/env sh

set -e

. $(dirname $0)/set-versions

ROOT_DIR=`pwd`
INSTALL_DIR=$1

APACHE2_DIR=${INSTALL_DIR}

mkdir -p "${INSTALL_DIR}"
# TODO: change to dependency configured externally 
whack install git+https://github.com/mwilliamson/whack-package-apache2 "${APACHE2_DIR}"

build_libxml() {
    # TODO: package libxml separately
    
    LIBXML_SRC_DIR=libxml2-${LIBXML_VERSION}
    LIBXML_DIR=${INSTALL_DIR}/libxml2
    
    tar xzf libxml2-${LIBXML_VERSION}.tar.gz
    cd ${LIBXML_SRC_DIR}
    ./configure --prefix=${LIBXML_DIR}
    make
    make install
    
    cd ${ROOT_DIR}
}

build_php() {
    build_libxml
    
    PHP_SRC_DIR=php-${PHP_VERSION}
    PHP_DIR=${INSTALL_DIR}
    
    tar xzf php-${PHP_VERSION}.tar.gz
    cd ${PHP_SRC_DIR}
    ./configure \
        --prefix=${PHP_DIR} \
        --bindir=${PHP_DIR}/.bin \
        --sbindir=${PHP_DIR}/.bin \
        --with-apxs2=${APACHE2_DIR}/bin/apxs \
        --with-libxml-dir=${LIBXML_DIR} \
        --with-mysql
    make
    make install
    cp php.ini-production ${PHP_DIR}/lib/php.ini
    
    cd ${ROOT_DIR}
}

build_php

#~ echo 'LoadModule php5_module modules/libphp5.so' >> ${INSTALL_DIR}/conf/httpd.conf
echo '<FilesMatch \.php$>
    SetHandler application/x-httpd-php
</FilesMatch>' >> ${INSTALL_DIR}/conf/httpd.conf
